name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Check codestyle
        run: git ls-files *.{c,h} | xargs clang-format -i --verbose src/main/chessviz.c src/lib/move.c src/lib/move.h src/lib/print.c src/lib/print.h && git diff --exit-code

      - name: Build application
        run: make
